steps:
- label: ":docker: build"
  plugins:
    - docker-compose#v3.7.0:
        build: app
  
- wait

- label: "test"
  command: "npm run test"
  plugins:
    - docker-compose#v3.7.0:
        run: app