steps:
  - label: ":docker: Build"
  plugins:
    - docker-compose#v3.7.0:
      build: app
    
  - wait

  - label: "deploy"
  command: .buildkite/scripts/deploy.sh
  plugins:
    - docker-compose#v3.7.0:
      run: app