steps:
- label: ":docker: build"
  command: "echo hello world"
  plugins:
    - docker-compose#v3.7.0:
        build: app
  
- wait

- label: "test"
  command: .buildkite/scripts/test.sh
  plugins:
    - docker-compose#v3.7.0:
        run: app